export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Design System Colors
        "on-secondary": "#00363e",
        "on-tertiary-container": "#292934",
        "surface-container-high": "#2a292f",
        "surface-bright": "#39383e",
        "surface-variant": "#35343a",
        "on-primary-fixed": "#23005c",
        "outline": "#958ea0",
        "surface-container": "#1f1f25",
        "on-surface": "#e4e1e9",
        "on-background": "#e4e1e9",
        "surface-container-lowest": "#0e0e13",
        "on-secondary-fixed-variant": "#004e5a",
        "secondary-fixed": "#a2eeff",
        "tertiary-container": "#918f9d",
        "tertiary-fixed": "#e3e1f0",
        "on-tertiary": "#302f3b",
        "primary-fixed-dim": "#d0bcff",
        "error": "#ffb4ab",
        "primary": "#d0bcff",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed-variant": "#5516be",
        "surface": "#131318",
        "on-secondary-container": "#00515d",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#1b1b26",
        "inverse-surface": "#e4e1e9",
        "on-error": "#690005",
        "surface-container-low": "#1b1b20",
        "surface-container-highest": "#35343a",
        "secondary-fixed-dim": "#2fd9f4",
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "tertiary": "#c7c5d4",
        "tertiary-fixed-dim": "#c7c5d4",
        "secondary-container": "#00cbe6",
        "on-surface-variant": "#cbc3d7",
        "surface-dim": "#131318",
        "on-tertiary-fixed-variant": "#464652",
        "background": "#131318",
        "on-secondary-fixed": "#001f25",
        "inverse-primary": "#6d3bd7",
        "outline-variant": "#494454",
        "on-error-container": "#ffdad6",
        "secondary": "#5de6ff",
        "surface-tint": "#d0bcff",
        "primary-container": "#a078ff",
        "inverse-on-surface": "#303036",
        // Keep violet alias for accent
        "violet": {
          "400": "#a78bfa",
          "500": "#8b5cf6",
          "600": "#7c3aed",
        }
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit-8": "32px",
        "unit-1": "4px",
        "gutter": "16px",
        "unit-3": "12px",
        "unit-4": "16px",
        "unit-6": "24px",
        "unit-2": "8px",
        "container-max": "1280px",
        "base": "4px",
        "unit-1.5": "6px",
        "unit-3.5": "14px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
